In [2]:
print('hello')

hello


In [3]:
import numpy as np

print(np.__version__)

2.5.2


In [4]:
import sys
print(sys.executable)  # 이 venv 폴더 안의 python.exe 경로가 나와야 정상
print(sys.version)

c:\sk-encoa\dl_workspace\.venv\Scripts\python.exe
3.12.13 (main, Jun 23 2026, 15:23:43) [MSC v.1944 64 bit (AMD64)]


In [ ]:
# uv add torch torchvision

import torch

# 버전확인
print(torch.__version__)

# cuda 지원 확인
print(torch.cuda.is_available())  # GPU 인식 여부

2.13.0+cpu
False


In [11]:
output = torch.tensor([1.0, 2.0, 3.0])

print("출력 결과 장치:",output.device)

출력 결과 장치: cpu


## 1.1 데이터로부터 직접 생성

In [17]:
a = torch.tensor([[1,2],[3,4]])
print(a)
print(type(a))
print(a.dtype)

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
torch.int64


In [19]:
# python 리스트로부터 생성
list_data = [[1,2,3],[4,5,6]]
print(f'list_data:{list_data}')
type(list_data)
tensor_from_list = torch.tensor(list_data, dtype = torch.float32)
print(f'List -> Tensor: { tensor_from_list}')
print(type(tensor_from_list))
print(tensor_from_list.dtype)
print(tensor_from_list.device)


list_data:[[1, 2, 3], [4, 5, 6]]
List -> Tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])
<class 'torch.Tensor'>
torch.float32
cpu


In [27]:
# numpy 배열로 부터 생성
np_array = np.array([10,20,30])
# from_numpy()으로 tensor()을 생성하면 메모리를 공유한다.
tensor_from_np = torch.tensor(np_array)
print(f'tensor_from_np:{tensor_from_np}')

tensor_from_np[0] = 999
print(f'np_array: {np_array}')                        #999
print(f'tensor_from_np: {tensor_from_np}')            #999

np_array[0] = 500
print(f'np_array: {np_array}')                        #500
print(f'tensor_from_np: {tensor_from_np}')            #500?

tensor_from_np:tensor([10, 20, 30])
np_array: [10 20 30]
tensor_from_np: tensor([999,  20,  30])
np_array: [500  20  30]
tensor_from_np: tensor([999,  20,  30])


## 1.2 특정 형태(Shape)와 값으로 초기화 (Structured Initialization)

In [ ]:
shape = (2,3)
print(f'zeros: {torch.zeros((shape))}')
print(f'ones: {torch.ones((shape))}')
print(f'empty: {torch.empty((shape))}')
print(f'full: {torch.full(shape, 3.)}')

# 범위 기반 생성
print(f'arange: {torch.arange(10)}')               # end
print(f'arange: {torch.arange(0,10)}')             # start, end
print(f'arange: {torch.arange(0,10,2)}')           # start, end, step  

print(f'linspace: {torch.linspace(1,10,5)}')       # start, end, step ( 1 부터 10까지 5등분)

zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones: tensor([[1., 1., 1.],
        [1., 1., 1.]])
empty: tensor([[1., 1., 1.],
        [1., 1., 1.]])
full: tensor([[3., 3., 3.],
        [3., 3., 3.]])
arange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])


## 1.3. 무작위 난수로 초기화 (Random Initialization)  
신경망의 초기 가중치(Weight)를 설정할 때 필수적으로 사용하는 생성 방식입니다.

- `torch.rand(*size)`: [0, 1) 범위의 **균등 분포(Uniform Distribution)** 난수 생성
- `torch.randn(*size)`: 평균이 0이고 표준편차가 1인 **표준 정규 분포(Standard Normal Distribution)** 난수 생성
- `torch.randint(low, high, size)`: [low, high) 범위의 **정수 난수** 생성
- `torch.randperm(n)`: 0부터 n-1까지의 정수를 무작위로 섞은 1차원 텐서 생성 (데이터 셔플링 시 유용)

In [ ]:
# 난수 생성 시 재현성을 위한 시드(Seed) 고정
torch.manual_seed(42)

print(f'rand: {torch.rand(2,2)}')
print(f'rand: {torch.rand((2,2))}')

print(f'randn: {torch.randn((2,2))}')
print(f'randint: {torch.randint(10, (2,2))}')
print(f'randint: {torch.randint(1, 10, (2,2))}')                     # low = 0, high, size = ()
print(f'randint: {torch.randint(low=1, high=10, size = (2,2))}')

print(f'randperm: {torch.randperm(10)}')                             # 0부터 n-1까지만의 정수를 무작위로 섞은 1차 텐서 생성

rand: tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
rand: tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])
randn: tensor([[-1.1229, -0.1863],
        [ 2.2082, -0.6380]])
randint: tensor([[5, 5],
        [7, 6]])
randint: tensor([[5, 9],
        [2, 6]])
randint: tensor([[9, 5],
        [3, 1]])
randperm: tensor([7, 2, 6, 8, 5, 9, 0, 3, 4, 1])


## 1.4. 기존 텐서의 속성을 복사하여 초기화 (`_like` 계열)

기존에 존재하는 텐서와 동일한 크기(Shape), 데이터 타입(dtype), 디바이스(device)를 유지하면서 내부 값만 새로 채우는 방법입니다.

In [ ]:
x = torch.tensor([[1,2,3],
                  [4,5,6]], dtype = torch.float32)
print(f'x: {x}')

x_zeros = torch.zeros_like(x)

print(f'zeros_like: {x_zeros}, dtype: {x_zeros.dtype}')

x_ones = torch.ones_like(x)
print(f'ones_like: {x_ones}, dtype: {x_ones.dtype}')

x_rand = torch.rand_like(x)
print(f'rand_like: {x_rand}, dtype: {x_rand.dtype}')

# randint_like()은 x의 타입이 float32이므로 그 타입을 그대로 따라서 사용이 된다.(주의)
x_randint = torch.randint_like(x,10)
print(f'randint_like: {x_randint}, dtype: {x_randint.dtype}')

x: tensor([[1., 2., 3.],
        [4., 5., 6.]])
zeros_like: tensor([[0., 0., 0.],
        [0., 0., 0.]]), dtype: torch.float32
ones_like: tensor([[1., 1., 1.],
        [1., 1., 1.]]), dtype: torch.float32
rand_like: tensor([[0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440]]), dtype: torch.float32
randint_like: tensor([[9., 5., 4.],
        [8., 8., 6.]]), dtype: torch.float32


## 1.5. 텐서의 주요 속성 (Attributes)

텐서를 생성할 때 지정하거나, 생성된 텐서의 상태를 확인할 수 있는 3가지 핵심 속성입니다.

In [55]:
# 속성을 명시하며 텐서 생성
tensor_attr = torch.ones((2, 3), dtype=torch.float16, device="cpu")

print("Shape (차원):", tensor_attr.shape)
print("Datatype (타입):", tensor_attr.dtype)
print("Device (장치):", tensor_attr.device)

# 타입 변경 및 디바이스 이동
tensor_float32 = tensor_attr.to(dtype=torch.float32)
print("변경된 Datatype:", tensor_float32.dtype)

# GPU가 사용 가능한 경우 CUDA 장치로 이동
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("이동된 Device:", device )

Shape (차원): torch.Size([2, 3])
Datatype (타입): torch.float16
Device (장치): cpu
변경된 Datatype: torch.float32
이동된 Device: cpu


# 2. 텐서 사이즈(Tensor Size)

PyTorch에서 Tensor Size(Shape)는 텐서의 각 차원(Dimension)에 배치된 요소의 개수를 나타내는 핵심 속성입니다. 모델 구조를 설계하거나 데이터를 전처리할 때 텐서의 크기와 모양을 정확히 파악하고 조작하는 것은 필수적입니다.

## 2.1 크기 및 차원 확인 (Size Inspection)

In [ ]:
x = torch.arange(24).reshape(2, 3, 4)     # (2, 3, 4) 크기의 3차원 텐서

print(f'size: {x.shape}')        # torch.Size([2, 3, 4])
print(f'ndim: {x.ndim}')         # 3
print(f'size: {x.size(0)}')      # size(dim) => size(0) => 2
print(f'numel: {x.numel()}')     # 24 : 텐서 내부의 전체요소갯수

size: torch.Size([2, 3, 4])
ndim: 3
size: 2
numel: 24


## 2.2 크기 변경 및 형상 조작 (Shape Manipulation)

In [77]:
x = torch.arange(24).reshape(2, 3, 4)    # 3차원 텐서

# view()와 reshape
x_view = x.view(2, 12)       # 2차원 행렬
x_auto = x.reshape(-1,6)
print(x_view)
print(x_auto)

# unsqueeze & squeeze
x_2d = torch.randn(3,4)
print(f'x_2d: {x_2d}')

# unsqeeze(axis) : 축을 추가할때 사용한다.(차원확대)
x_unsqueeze = x_2d.unsqueeze(1)               # 0으로 설정하면 batch 차원 추가함
print(f'x_unsqueeze : {x_unsqueeze.shape}')   # np.newaxis

# squeeze()은 크기가 1인 차원을 축소한다.
x_squeeze = x_unsqueeze.squeeze()
print(f'x_squeeze : {x_squeeze.shape}')

# 4. permute (차원 재배치)
img_tensor = torch.randn(32, 3, 224, 224) # (Batch, Channel, Height, Width)
img_permuted = img_tensor.permute(0, 2, 3, 1) # (Batch, Height, Width, Channel)
print("\nPermuted Shape:", img_permuted.shape) # torch.Size([32, 224, 224, 3])

# 5. expand vs repeat
a = torch.tensor([[1], [2]])       # Shape: (2, 1)
a_expanded = a.expand(2, 4)        # 메모리 복사 없이 (2, 4)로 확장
a_repeated = a.repeat(1, 4)        # 실제 데이터를 4번 복사하여 (2, 4) 생성
print(f'\nexpend: {a.expand(2, 4)}')
print(f'\nrepeat: {a.repeat(1, 4)}')

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
x_2d: tensor([[ 0.6689,  1.9332, -1.0452,  0.1557],
        [-0.9031, -0.6827,  0.8091,  1.4059],
        [-0.4840, -1.0572,  0.0480, -1.5055]])
x_unsqueeze : torch.Size([3, 1, 4])
x_squeeze : torch.Size([3, 4])

Permuted Shape: torch.Size([32, 224, 224, 3])

expend: tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]])

repeat: tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]])


# 3. 인덱싱, 슬라이싱 및 결합 (Indexing, Slicing & Joining)

NumPy와 동일한 방식의 인덱싱 및 슬라이싱을 지원하며, 여러 텐서를 연결할 수 있습니다.

PyTorch의 인덱싱, 슬라이싱, 결합(Joining)은 텐서에서 특정 데이터를 추출하거나 여러 텐서를 조합할 때 사용하는 핵심 연산입니다. NumPy의 표현식과 대부분 호환됩니다.

## 3.1 기본 인덱싱 및 슬라이싱 (Basic Indexing & Slicing)

차원별 인덱스를 지정하거나 `start:end:step` 형식을 사용하여 텐서의 특정 부분에 접근합니다.

In [81]:
import torch

# 3x4 크기의 2차원 텐서 생성
x = torch.tensor([[ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12]])

# 1. 단일 요소 접근 (1행 2열 -> 값: 7)
print(f'x: {x[1,2]}')                # 7
print(f'x: {x[1,2].item()}')                # 7

# 2. 특정 행/열 전체 추출
print("2-1. 첫 번째 행 전체 (0, :):", x[0, :])
print("2-2. 마지막 열 전체 (:, -1):", x[:, -1])

# 3. 범위 슬라이싱 (0~1행, 1~2열 추출)
# [start:end]에서 end는 포함되지 않음
print("3. 부분 텐서 추출:\n", x[0:2, 1:3])

# 4. 간격 지정 슬라이싱 (step=2)
print("4. 2칸 간격 추출:", x[:, ::2])

x: 7
x: 7
2-1. 첫 번째 행 전체 (0, :): tensor([1, 2, 3, 4])
2-2. 마지막 열 전체 (:, -1): tensor([ 4,  8, 12])
3. 부분 텐서 추출:
 tensor([[2, 3],
        [6, 7]])
4. 2칸 간격 추출: tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])


## 3.2 고급 인덱싱 (Advanced Indexing)

조건을 이용해 데이터를 필터링하는 **불리언 마스킹**과 특정 위치의 인덱스를 배열로 전달해 가져오는 **팬시 인덱싱** 방식입니다.

### 주요 개념

- **불리언 마스킹 (Boolean Indexing):** 텐서에 조건식을 적용하여 `True` 위치의 값만 1차원 텐서로 추출합니다.
- **`torch.index_select()`:** 특정 차원(`dim`)을 기준으로 원하는 인덱스 번호 들을 모아서 선택합니다.

In [82]:
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

# 1. 불리언 마스킹 (50보다 큰 요소만 추출)
mask = x > 50
print("마스크 (Boolean Tensor):\n", mask)
print("50보다 큰 값만 추출:", x[mask])  # 1차원 텐서로 반환됨

# 2. 인덱스 리스트를 활용한 추출 (팬시 인덱싱)
# 0행과 2행 추출
rows = torch.tensor([0, 2])
print("\n0행과 2행 추출:\n", x[rows])

# 3. torch.index_select 사용 (dim=1: 열 기준 추출)
cols = torch.tensor([0, 2]) # 0열과 2열 선택
selected_cols = torch.index_select(x, dim=1, index=cols)
print("0열과 2열 추출 (index_select):\n", selected_cols)

마스크 (Boolean Tensor):
 tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
50보다 큰 값만 추출: tensor([60, 70, 80, 90])

0행과 2행 추출:
 tensor([[10, 20, 30],
        [70, 80, 90]])
0열과 2열 추출 (index_select):
 tensor([[10, 30],
        [40, 60],
        [70, 90]])


## 3.3 텐서 결합 (Joining Tensors)

여러 텐서를 하나로 합치는 연산으로, 기존 차원을 따라 붙이는 `torch.cat`과 새로운 차원을 생성하며 쌓는 `torch.stack`이 대표적입니다.

In [83]:
t1 = torch.tensor([[1, 2],
                   [3, 4]])

t2 = torch.tensor([[5, 6],
                   [7, 8]])

# 1. torch.cat (기존 차원 이어붙이기)
# dim=0: 세로 방향(행)으로 붙임
cat_dim0 = torch.cat([t1, t2], dim=0)
print("torch.cat (dim=0) Shape:", cat_dim0.shape)
print(cat_dim0)

# dim=1: 가로 방향(열)으로 붙임
cat_dim1 = torch.cat([t1, t2], dim=1)
print("\ntorch.cat (dim=1) Shape:", cat_dim1.shape)
print(cat_dim1)

# 2. torch.stack (새로운 차원 생성하며 쌓기)
# dim=0: 맨 앞에 새로운 차원 추가 (2, 2, 2)
stacked = torch.stack([t1, t2], dim=0)
print("\ntorch.stack (dim=0) Shape:", stacked.shape)
print(stacked)

torch.cat (dim=0) Shape: torch.Size([4, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

torch.cat (dim=1) Shape: torch.Size([2, 4])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

torch.stack (dim=0) Shape: torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [86]:
x = torch.randn(2,3)
torch.stack((x,x),dim=0)

tensor([[[-0.9788, -0.8931,  1.5476],
         [ 0.0516,  0.2505, -0.8700]],

        [[-0.9788, -0.8931,  1.5476],
         [ 0.0516,  0.2505, -0.8700]]])

In [87]:
x = torch.randn(2,3)
torch.stack((x,x),dim=1)

tensor([[[ 0.4527,  0.4807, -0.6271],
         [ 0.4527,  0.4807, -0.6271]],

        [[-1.7369,  0.1114,  0.5176],
         [-1.7369,  0.1114,  0.5176]]])

## 3.4 텐서 분할 (Splitting Tensors)

결합의 반대 연산으로, 하나의 텐서를 여러 개로 나눌 때 사용합니다.

- **`torch.split(tensor, split_size_or_sections, dim=0)`**: 지정한 크기 단위로 텐서를 분할합니다.
- **`torch.chunk(tensor, chunks, dim=0)`**: 지정한 개수(`chunks`)만큼 균등하게 등분합니다.

In [84]:
x = torch.arange(12).reshape(4, 3) # 4행 3열 텐서
print("분할할 원본 텐서 (4x3):\n", x)

# 1. torch.split: 행 방향(dim=0)으로 2행씩 분할
split_result = torch.split(x, split_size_or_sections=2, dim=0)
print("\nsplit (크기 2씩 분할 결과):")
for t in split_result:
    print(t)

# 2. torch.chunk: 행 방향(dim=0)으로 총 2개의 덩어리로 분할
chunk_result = torch.chunk(x, chunks=2, dim=0)
print("\nchunk (2개로 등분 결과):")
for t in chunk_result:
    print(t)

분할할 원본 텐서 (4x3):
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

split (크기 2씩 분할 결과):
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

chunk (2개로 등분 결과):
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])


# 4. Tensor Data Type

PyTorch의 데이터 타입(`dtype`)은 텐서가 메모리에서 차지하는 크기, 연산 정밀도(Precision), 그리고 사용할 수 있는 하드웨어 가속 범위를 결정합니다.

### 4.1 주요 데이터 타입 종류 (Data Types Overview)

PyTorch는 실수, 정수, 논리, 복소수 등 다양한 데이터 타입을 제공합니다.

### 4.2 기본 데이터 타입 확인 및 변경 (Default dtype)

NumPy의 기본 실수형은 `float64`인 반면, PyTorch의 기본 실수형은 `float32`입니다

In [88]:
import torch

# 1. 기본 생성 시 타입 확인
float_tensor = torch.tensor([1.0, 2.0, 3.0])
int_tensor = torch.tensor([1, 2, 3])

print("기본 실수 타입:", float_tensor.dtype) # torch.float32
print("기본 정수 타입:", int_tensor.dtype)   # torch.int64

# 2. 전역 기본 실수 타입 확인 및 변경
print("현재 기본 dtype:", torch.get_default_dtype())

# 기본 타입을 float64로 변경 (필요한 경우에만 사용)
torch.set_default_dtype(torch.float64)
print("변경 후 기본 dtype:", torch.get_default_dtype())

# 다시 원복
torch.set_default_dtype(torch.float32)

기본 실수 타입: torch.float32
기본 정수 타입: torch.int64
현재 기본 dtype: torch.float32
변경 후 기본 dtype: torch.float64


### 4.3 데이터 타입 지정 및 형변환 (Type Casting)

텐서를 생성할 때 `dtype`을 명시하거나, 기존 텐서의 타입을 변환(Casting)할 수 있습니다.

In [89]:
# 1. 생성 시 dtype 명시
x_float16 = torch.tensor([1.5, 2.5], dtype=torch.float16)
x_int32 = torch.zeros((2, 2), dtype=torch.int32)

# 2. 형변환 방식 1: .to() 메서드 (권장 표준 패턴)
# 디바이스(CPU/GPU) 변경과 dtype 변경을 동시에 수행할 수 있어 가장 많이 쓰입니다.
x_converted = x_float16.to(torch.float32)
print("to() 변환 후:", x_converted.dtype)

# 3. 형변환 방식 2: 축약 메서드 (.float(), .long(), .bool() 등)
x_long = x_float16.long()   # float16 -> int64 (소수점 버림 처리)
x_bool = x_float16.bool()   # 0이 아니면 True
print("long() 변환 후 (값):", x_long)
print("bool() 변환 후 (값):", x_bool)

# 4. 형변환 방식 3: 다른 텐서의 dtype 추종 (.type_as())
target_tensor = torch.ones(2, dtype=torch.float64)
x_matched = x_float16.type_as(target_tensor)
print("type_as() 변환 후:", x_matched.dtype)

to() 변환 후: torch.float32
long() 변환 후 (값): tensor([1, 2])
bool() 변환 후 (값): tensor([True, True])
type_as() 변환 후: torch.float64


### 4.4 자동 형변환 및 승격 (Type Promotion)

서로 다른 `dtype`을 가진 텐서끼리 연산하면, 데이터 손실을 막기 위해 **더 정밀하거나 넓은 범위를 표현할 수 있는 타입으로 자동 승격**됩니다.

In [90]:
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
float_tensor = torch.tensor([0.5, 1.5, 2.5], dtype=torch.float32)

# int32 + float32 -> float32로 자동 승격
result = int_tensor + float_tensor
print("연산 결과:", result)
print("자동 승격된 dtype:", result.dtype) # torch.float32

연산 결과: tensor([1.5000, 3.5000, 5.5000])
자동 승격된 dtype: torch.float32


### 4.5 실전 딥러닝에서의 주요 활용법

- **`torch.float32` (FP32):** 모델의 가중치(Weight), 편향(Bias), 입력 데이터의 기본 타입입니다.
- **`torch.float16` / `torch.bfloat16` (FP16 / BF16):** 대규모 언어 모델(LLM)이나 이미지 모델 학습 시 GPU 메모리 절약과 연산 속도 향상을 위해 **혼합 정밀도(AMP, Automatic Mixed Precision)** 기술과 함께 사용합니다.
- **`torch.int64` (`LongTensor`):** `nn.CrossEntropyLoss`의 클래스 라벨 타깃 데이터나 `nn.Embedding` 레이어의 인덱스 입력값은 반드시 `int64` 형태여야 에러가 나지 않습니다.
- **`torch.uint8` / `torch.bool`:** 이미지를 로드할 때(0~255)나 특정 조건에 맞는 요소만 걸러내는 마스킹(Masking) 연산에 자주 쓰입니다.

# 5. Numpy to Tensor, Tensor to Numpy

PyTorch와 NumPy는 데이터 표현 방식이 매우 유사하지만, 메모리 공유 여부와 GPU/자동 미분(Autograd) 지원에 따른 차이가 있습니다.

## 5.1 NumPy $\rightarrow$ Tensor 변환

NumPy 배열을 PyTorch 텐서로 변환할 때는 **메모리 공유(Zero-copy) 여부**와 데이터 타입(dtype)에 주의해야 합니다.

### 주의할 점: 데이터 타입 (dtype)

NumPy의 기본 실수형은 `float64(double)`입니다. PyTorch 모델의 기본 입력은 `float32(float)`이므로, 변환 후 `.float()` 또는 `.to(torch.float32)`를 붙여 타입 변환을 해주는 경우가 많습니다.

In [92]:
import torch
import numpy as np

np_arr = np.array([1.0, 2.0, 3.0]) # 기본 dtype: float64

# 1. torch.from_numpy(): 메모리 공유 (Zero-copy)
t_from_np = torch.from_numpy(np_arr)

# 2. torch.as_tensor(): 범용 메모리 공유
t_as_tensor = torch.as_tensor(np_arr)

# 3. torch.tensor(): 완전 복사 (독립 메모리)
t_copy = torch.tensor(np_arr)

# 4. 딥러닝 표준 패턴: Tensor 변환 + float32 형변환
t_float32 = torch.from_numpy(np_arr).float()

# 메모리 공유 검증
np_arr[0] = 999.0
print("from_numpy 결과 (값 변경됨):", t_from_np[0].item()) # 999.0
print("tensor() 복사 결과 (독립적):", t_copy[0].item())       # 1.0

from_numpy 결과 (값 변경됨): 999.0
tensor() 복사 결과 (독립적): 1.0


## 5.2. Tensor  $\rightarrow$ NumPy 변환

텐서를 NumPy 배열로 변환할 때는 `tensor.numpy()`를 사용합니다. 기본적으로 메모리를 공유하지만, **2가지 제약 조건**이 있습니다.

### 핵심 제약 조건 및 해결책

1. **GPU 텐서 제약:** NumPy는 CPU 메모리만 다룰 수 있으므로, GPU(`cuda`/`mps`)에 있는 텐서는 먼저 CPU로 이동해야 합니다 (`.cpu()`).
2. **Autograd(기록 추적) 제약:** 계산 그래프가 연결된(`requires_grad=True`) 텐서는 추적을 끊어주어야 변환할 수 있습니다 (`.detach()`).

### 실전 표준 관용구 (The Golden Standard)

In [94]:
# 가장 완전하고 안전한 변환 패턴
# np_array = tensor.detach().cpu().numpy()

In [95]:
import torch

# 상황 1: CPU 기반, 연산 기록이 없는 일반 텐서
t_simple = torch.tensor([10.0, 20.0, 30.0])
np_simple = t_simple.numpy() # 바로 변환 가능 (메모리 공유)

# 상황 2: GPU 사용 + 연산 기록(Autograd)이 활성화된 텐서
device = "cuda" if torch.cuda.is_available() else "cpu"
t_complex = torch.tensor([1.0, 2.0, 3.0], requires_grad=True, device=device)

# t_complex.numpy() 실행 시 RuntimeError 발생!
# 에러 예시: Can't call numpy() on Tensor that requires grad / cuda device

# 표준 해결책: detach() -> cpu() -> numpy()
np_safe = t_complex.detach().cpu().numpy()

print("안전하게 변환된 NumPy 배열:", np_safe)
print("타입:", type(np_safe))

안전하게 변환된 NumPy 배열: [1. 2. 3.]
타입: <class 'numpy.ndarray'>


## 5.3 핵심 요약 및 체크리스트

- **속도/메모리 최적화가 필요할 때:** `torch.from_numpy()` 및 `tensor.numpy()` 사용 (메모리 포인터 공유)
- **안전하게 복사본을 만들 때:** `torch.tensor(np_arr)` 또는 `tensor.clone().numpy()` 사용
- **모델 출력값(Loss, Prediction)을 NumPy로 변환할 때:** 반드시 **`.detach().cpu().numpy()`** 패턴을 적용하여 그래프 추적 및 GPU 메모리 종속성 해제

# 6. 수학적 연산 (Math Operations)

PyTorch의 수학적 연산(Math Operations)은 신경망의 순전파(Forward Pass), 손실 계산, 가중치 업데이트 등 모든 계산 과정의 기반이 됩니다. 크게 **요소별 연산 및 브로드캐스팅**, **행렬 연산**, **집계 연산**, **제자리 연산**으로 나뉩니다.

## 6.1 요소별 연산 (Element-wise Operations) & 브로드캐스팅

두 텐서의 **동일한 위치에 있는 요소끼리** 1:1로 연산을 수행합니다. Shape이 서로 다른 경우 **브로드캐스팅(Broadcasting)** 규칙에 따라 크기가 자동으로 확장되어 계산됩니다.

### 주요 개념

- **기본 연산자:** `+`, , , `/`, `*` (제곱)
- **특수 수학 함수:** `torch.abs()`, `torch.exp()`, `torch.log()`, `torch.sqrt()`, `torch.pow()`
- **브로드캐스팅 규칙:** 뒤쪽 차원(Rightmost dimension)부터 비교하여 크기가 같거나 한쪽이 `1`인 경우 자동 확장 연산됩니다.

In [ ]:
import torch

a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

# 1. 기본 요소별 연산
print("1-1. 덧셈 (a + b):\n", a + b)           # torch.add(a, b)와 동일
print("1-2. 요소별 곱셈 (a * b):\n", a * b)    # torch.mul(a, b)와 동일 (Hadamard product)
print("1-3. 나눗셈 (a / b):\n", a / b)        # torch.div(a, b)와 동일

# 2. 수학 함수 연산
print("\n2-1. 지수 함수 (exp):\n", torch.exp(a))
print("2-2. 제곱근 (sqrt):\n", torch.sqrt(a))

# 3. 브로드캐스팅 (Broadcasting)
# (2, 2) 텐서 + (1, 2) 텐서 -> (1, 2) 텐서가 아래로 2줄 복사되어 연산됨
c = torch.tensor([[10.0, 20.0]]) # Shape: (1, 2)
print("\n3. 브로드캐스팅 덧셈 (a + c):\n", a + c)

## 6.2 행렬 연산 및 선형대수 (Matrix Operations & Linear Algebra)

신경망의 선형 레이어(Linear Layer) 연산에서 가장 빈번하게 사용되는 선형대수 연산입니다.

### 주요 함수

- **`a @ b` 또는 `torch.matmul(a, b)`:** 일반적인 **행렬 곱(Matrix Multiplication)**. 고차원 텐서에 대한 브로드캐스팅 행렬 곱도 지원합니다.
- **`torch.mm(a, b)`:** **2차원 행렬 전용** 행렬 곱 (브로드캐스팅 미지원, 속도 엄격함).
- **`torch.bmm(a, b)`:** **배치 행렬 곱 (Batch Matrix Multiplication)**. 3차원 텐서 `(B, N, M) @ (B, M, P) -> (B, N, P)` 처리.
- **`tensor.T` 또는 `torch.transpose(tensor, dim0, dim1)`:** 전치 행렬(Transpose).
- **torch.dot(a, b)** : 백터의 내적을 구함

In [96]:
m1 = torch.tensor([[1, 2],
                   [3, 4]]) # Shape: (2, 2)
m2 = torch.tensor([[5, 6],
                   [7, 8]]) # Shape: (2, 2)

# 1. 행렬 곱 (Matrix Multiplication)
print("1. 행렬 곱 (m1 @ m2):\n", m1 @ m2) # 또는 torch.matmul(m1, m2)

# 2. 전치 행렬 (Transpose)
print("\n2. m1 전치 행렬 (m1.T):\n", m1.T)

# 3. 배치 행렬 곱 (bmm) - 차원: (Batch_size, Row, Col)
batch_a = torch.randn(2, 3, 4) # 배치 크기 2, (3x4) 행렬 2개
batch_b = torch.randn(2, 4, 5) # 배치 크기 2, (4x5) 행렬 2개

bmm_res = torch.bmm(batch_a, batch_b)
print("\n3. Batch Matmul 결과 Shape:", bmm_res.shape) # (2, 3, 5)

# 4. 벡터 내적(dot)
dot_a = torch.FloatTensor([1, 2, 3])
dot_b = torch.FloatTensor([2, 3, 4])
dot_res= torch.dot(dot_a , dot_b )
print("/n4. dot 벡터 내적 결과", dot_res)

1. 행렬 곱 (m1 @ m2):
 tensor([[19, 22],
        [43, 50]])

2. m1 전치 행렬 (m1.T):
 tensor([[1, 3],
        [2, 4]])

3. Batch Matmul 결과 Shape: torch.Size([2, 3, 5])
/n4. dot 벡터 내적 결과 tensor(20.)


## 6.3 집계 연산 (Reduction Operations)

텐서 내부 요소들의 합, 평균, 최댓값 등을 구하여 차원을 줄이거나 요약하는 연산입니다.

### 주요 개념 및 옵션

- **`dim` 매개변수:** 연산을 수행할 축(차원)을 지정합니다. (지정하지 않으면 텐서 전체 요소 대상)
- **`keepdim=True`:** 연산 후 감소되는 차원 축을 삭제하지 않고 **크기 `1`로 유지**하여, 이후 브로드캐스팅 연산이 용이하도록 합니다.
- **`argmax()` / `argmin()`:** 최댓값/최솟값이 위치한 인덱스(Index)를 반환합니다. (분류 문제에서 예측 클래스 추출 시 필수 사용)

In [97]:
x = torch.tensor([[1.0, 5.0, 3.0],
                  [4.0, 2.0, 6.0]]) # Shape: (2, 3)

# 1. 전체 요소 집계
print("전체 합:", x.sum().item())
print("전체 평균:", x.mean().item())

# 2. 차원(dim) 기준 집계
# dim=0: 행 방향(세로)으로 뭉쳐서 연산 -> 결과 Shape: (3,)
print("\n열 기준(dim=0) 평균:", x.mean(dim=0))

# dim=1: 열 방향(가로)으로 뭉쳐서 연산 -> 결과 Shape: (2,)
print("행 기준(dim=1) 최댓값:", x.max(dim=1).values)

# 3. keepdim=True 옵션
sum_keepdim = x.sum(dim=1, keepdim=True)
print("\nkeepdim=True 적용 합 Shape:", sum_keepdim.shape) # (2, 1)

# 4. Argmax (최댓값의 인덱스 위치)
print("\n행 기준 가장 큰 값의 인덱스 (dim=1):", x.argmax(dim=1)) # [1, 2]

전체 합: 21.0
전체 평균: 3.5

열 기준(dim=0) 평균: tensor([2.5000, 3.5000, 4.5000])
행 기준(dim=1) 최댓값: tensor([5., 6.])

keepdim=True 적용 합 Shape: torch.Size([2, 1])

행 기준 가장 큰 값의 인덱스 (dim=1): tensor([1, 2])


## 6.4 제자리 연산 (In-place Operations)

새로운 텐서를 생성해 메모리를 할당하지 않고, **기존 텐서의 메모리 공간에 연산 결과를 즉시 덮어쓰는** 연산입니다.

### 규칙 및 주의사항

- **메서드 이름 뒤에 언더스코어(`_`)가 붙습니다.** (예: `add_()`, `mul_()`, `zero_()`)
- **메모리 절약:** 메모리 재할당 오버헤드를 줄일 수 있습니다.
- **Autograd 주의점:** 역전파(Backward Pass) 계산 시 미분에 필요한 이전 상태 값이 파괴될 수 있으므로, **자동 미분이 적용되는 가중치 텐서에는 In-place 연산을 함부로 사용해서는 안 됩니다.**

In [98]:
x = torch.tensor([1.0, 2.0, 3.0])
print("초기 메모리 주소:", id(x))

# Out-of-place 연산 (새로운 텐서 생성 -> 주소 변경됨)
x_new = x + 5.0
print("Out-of-place 후 x 주소:", id(x))

# In-place 연산 (기존 텐서 메모리에 즉시 반영 -> 주소 동일)
x.add_(5.0)
print("In-place 연산 후 x 값:", x)
print("In-place 후 x 주소:", id(x)) # 초기 주소와 동일함

# 모든 요소를 0으로 초기화
x.zero_()
print("zero_() 적용 후:", x)

초기 메모리 주소: 2152629705120
Out-of-place 후 x 주소: 2152629705120
In-place 연산 후 x 값: tensor([6., 7., 8.])
In-place 후 x 주소: 2152629705120
zero_() 적용 후: tensor([0., 0., 0.])
