In [1]:
print('hello')

hello


In [2]:
import numpy as np

print(np.__version__)

2.5.2


In [3]:
import sys
print(sys.executable)  # 이 venv 폴더 안의 python.exe 경로가 나와야 정상
print(sys.version)

c:\SKN35_kim\DL_WORKSPACE\.venv\Scripts\python.exe
3.12.13 (main, Jun 23 2026, 15:23:43) [MSC v.1944 64 bit (AMD64)]


In [4]:
# uv add torch torchvision

import torch

# 버전확인
print(torch.__version__)

# cuda 지원 확인
print(torch.cuda.is_available())  # GPU 인식 여부

2.13.0+cpu
False


In [5]:
output = torch.tensor([1.0, 2.0, 3.0])

print("출력 결과 장치:",output.device)

출력 결과 장치: cpu


## 1.1 데이터로부터 직접 생성

In [6]:
a = torch.tensor([[1,2],[3,4]])
print(a)
print(type(a))
print(a.dtype)

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
torch.int64


In [7]:
# python 리스트로부터 생성
list_data = [[1,2,3],[4,5,6]]
print(f'list_data:{list_data}')
type(list_data)
tensor_from_list = torch.tensor(list_data, dtype = torch.float32)
print(f'List -> Tensor: { tensor_from_list}')
print(type(tensor_from_list))
print(tensor_from_list.dtype)
print(tensor_from_list.device)


list_data:[[1, 2, 3], [4, 5, 6]]
List -> Tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])
<class 'torch.Tensor'>
torch.float32
cpu


In [8]:
# numpy 배열로 부터 생성
np_array = np.array([10,20,30])
# from_numpy()으로 tensor()을 생성하면 메모리를 공유한다.
tensor_from_np = torch.tensor(np_array)
print(f'tensor_from_np:{tensor_from_np}')

tensor_from_np[0] = 999
print(f'np_array: {np_array}')                        #999
print(f'tensor_from_np: {tensor_from_np}')            #999

np_array[0] = 500
print(f'np_array: {np_array}')                        #500
print(f'tensor_from_np: {tensor_from_np}')            #500?

tensor_from_np:tensor([10, 20, 30])
np_array: [10 20 30]
tensor_from_np: tensor([999,  20,  30])
np_array: [500  20  30]
tensor_from_np: tensor([999,  20,  30])


## 1.2 특정 형태(Shape)와 값으로 초기화 (Structured Initialization)

In [9]:
shape = (2,3)
print(f'zeros: {torch.zeros((shape))}')
print(f'ones: {torch.ones((shape))}')
print(f'empty: {torch.empty((shape))}')
print(f'full: {torch.full(shape, 3.)}')

# 범위 기반 생성
print(f'arange: {torch.arange(10)}')               # end
print(f'arange: {torch.arange(0,10)}')             # start, end
print(f'arange: {torch.arange(0,10,2)}')           # start, end, step  

print(f'linspace: {torch.linspace(1,10,5)}')       # start, end, step ( 1 부터 10까지 5등분)

zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones: tensor([[1., 1., 1.],
        [1., 1., 1.]])
empty: tensor([[-5.2008e+02,  1.1365e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
full: tensor([[3., 3., 3.],
        [3., 3., 3.]])
arange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])


## 1.3. 무작위 난수로 초기화 (Random Initialization)  
신경망의 초기 가중치(Weight)를 설정할 때 필수적으로 사용하는 생성 방식입니다.

- `torch.rand(*size)`: [0, 1) 범위의 **균등 분포(Uniform Distribution)** 난수 생성
- `torch.randn(*size)`: 평균이 0이고 표준편차가 1인 **표준 정규 분포(Standard Normal Distribution)** 난수 생성
- `torch.randint(low, high, size)`: [low, high) 범위의 **정수 난수** 생성
- `torch.randperm(n)`: 0부터 n-1까지의 정수를 무작위로 섞은 1차원 텐서 생성 (데이터 셔플링 시 유용)

In [10]:
# 난수 생성 시 재현성을 위한 시드(Seed) 고정
torch.manual_seed(42)

print(f'rand: {torch.rand(2,2)}')
print(f'rand: {torch.rand((2,2))}')

print(f'randn: {torch.randn((2,2))}')
print(f'randint: {torch.randint(10, (2,2))}')
print(f'randint: {torch.randint(1, 10, (2,2))}')                     # low = 0, high, size = ()
print(f'randint: {torch.randint(low=1, high=10, size = (2,2))}')

print(f'randperm: {torch.randperm(10)}')                             # 0부터 n-1까지만의 정수를 무작위로 섞은 1차 텐서 생성

rand: tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
rand: tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])
randn: tensor([[-1.1229, -0.1863],
        [ 2.2082, -0.6380]])
randint: tensor([[5, 5],
        [7, 6]])
randint: tensor([[5, 9],
        [2, 6]])
randint: tensor([[9, 5],
        [3, 1]])
randperm: tensor([7, 2, 6, 8, 5, 9, 0, 3, 4, 1])


## 1.4. 기존 텐서의 속성을 복사하여 초기화 (`_like` 계열)

기존에 존재하는 텐서와 동일한 크기(Shape), 데이터 타입(dtype), 디바이스(device)를 유지하면서 내부 값만 새로 채우는 방법입니다.

In [11]:
x = torch.tensor([[1,2,3],
                  [4,5,6]], dtype = torch.float32)
print(f'x: {x}')

x_zeros = torch.zeros_like(x)

print(f'zeros_like: {x_zeros}, dtype: {x_zeros.dtype}')

x_ones = torch.ones_like(x)
print(f'ones_like: {x_ones}, dtype: {x_ones.dtype}')

x_rand = torch.rand_like(x)
print(f'rand_like: {x_rand}, dtype: {x_rand.dtype}')

# randint_like()은 x의 타입이 float32이므로 그 타입을 그대로 따라서 사용이 된다.(주의)
x_randint = torch.randint_like(x,10)
print(f'randint_like: {x_randint}, dtype: {x_randint.dtype}')

x: tensor([[1., 2., 3.],
        [4., 5., 6.]])
zeros_like: tensor([[0., 0., 0.],
        [0., 0., 0.]]), dtype: torch.float32
ones_like: tensor([[1., 1., 1.],
        [1., 1., 1.]]), dtype: torch.float32
rand_like: tensor([[0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104]]), dtype: torch.float32
randint_like: tensor([[9., 7., 3.],
        [3., 4., 3.]]), dtype: torch.float32


## 1.5. 텐서의 주요 속성 (Attributes)

텐서를 생성할 때 지정하거나, 생성된 텐서의 상태를 확인할 수 있는 3가지 핵심 속성입니다.

In [12]:
# 속성을 명시하며 텐서 생성
tensor_attr = torch.ones((2, 3), dtype=torch.float16, device="cpu")

print("Shape (차원):", tensor_attr.shape)
print("Datatype (타입):", tensor_attr.dtype)
print("Device (장치):", tensor_attr.device)

# 타입 변경 및 디바이스 이동
tensor_float32 = tensor_attr.to(dtype=torch.float32)
print("변경된 Datatype:", tensor_float32.dtype)

# GPU가 사용 가능한 경우 CUDA 장치로 이동
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("이동된 Device:", device )

Shape (차원): torch.Size([2, 3])
Datatype (타입): torch.float16
Device (장치): cpu
변경된 Datatype: torch.float32
이동된 Device: cpu


# 2. 텐서 사이즈(Tensor Size)

PyTorch에서 Tensor Size(Shape)는 텐서의 각 차원(Dimension)에 배치된 요소의 개수를 나타내는 핵심 속성입니다. 모델 구조를 설계하거나 데이터를 전처리할 때 텐서의 크기와 모양을 정확히 파악하고 조작하는 것은 필수적입니다.

## 2.1 크기 및 차원 확인 (Size Inspection)

In [13]:
x = torch.arange(24).reshape(2, 3, 4)     # (2, 3, 4) 크기의 3차원 텐서

print(f'size: {x.shape}')        # torch.Size([2, 3, 4])
print(f'ndim: {x.ndim}')         # 3
print(f'size: {x.size(0)}')      # size(dim) => size(0) => 2
print(f'numel: {x.numel()}')     # 24 : 텐서 내부의 전체요소갯수

size: torch.Size([2, 3, 4])
ndim: 3
size: 2
numel: 24


## 2.2 크기 변경 및 형상 조작 (Shape Manipulation)

In [14]:
x = torch.arange(24).reshape(2, 3, 4)    # 3차원 텐서

# view()와 reshape
x_view = x.view(2, 12)       # 2차원 행렬
x_auto = x.reshape(-1,6)
print(x_view)
print(x_auto)

# unsqueeze & squeeze
x_2d = torch.randn(3,4)
print(f'x_2d: {x_2d}')

# unsqeeze(axis) : 축을 추가할때 사용한다.(차원확대)
x_unsqueeze = x_2d.unsqueeze(1)               # 0으로 설정하면 batch 차원 추가함
print(f'x_unsqueeze : {x_unsqueeze.shape}')   # np.newaxis

# squeeze()은 크기가 1인 차원을 축소한다.
x_squeeze = x_unsqueeze.squeeze()
print(f'x_squeeze : {x_squeeze.shape}')

# 4. permute (차원 재배치)
img_tensor = torch.randn(32, 3, 224, 224) # (Batch, Channel, Height, Width)
img_permuted = img_tensor.permute(0, 2, 3, 1) # (Batch, Height, Width, Channel)
print("\nPermuted Shape:", img_permuted.shape) # torch.Size([32, 224, 224, 3])

# 5. expand vs repeat
a = torch.tensor([[1], [2]])       # Shape: (2, 1)
a_expanded = a.expand(2, 4)        # 메모리 복사 없이 (2, 4)로 확장
a_repeated = a.repeat(1, 4)        # 실제 데이터를 4번 복사하여 (2, 4) 생성
print(f'\nexpend: {a.expand(2, 4)}')
print(f'\nrepeat: {a.repeat(1, 4)}')

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
x_2d: tensor([[-1.0186, -0.4180, -0.2935,  1.4329],
        [ 0.5312, -0.2483, -0.1735,  1.3850],
        [ 0.7045,  1.2197, -0.6778, -0.5920]])
x_unsqueeze : torch.Size([3, 1, 4])
x_squeeze : torch.Size([3, 4])

Permuted Shape: torch.Size([32, 224, 224, 3])

expend: tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]])

repeat: tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]])


# 3. 인덱싱, 슬라이싱 및 결합 (Indexing, Slicing & Joining)

NumPy와 동일한 방식의 인덱싱 및 슬라이싱을 지원하며, 여러 텐서를 연결할 수 있습니다.

PyTorch의 인덱싱, 슬라이싱, 결합(Joining)은 텐서에서 특정 데이터를 추출하거나 여러 텐서를 조합할 때 사용하는 핵심 연산입니다. NumPy의 표현식과 대부분 호환됩니다.

## 3.1 기본 인덱싱 및 슬라이싱 (Basic Indexing & Slicing)

차원별 인덱스를 지정하거나 `start:end:step` 형식을 사용하여 텐서의 특정 부분에 접근합니다.

In [15]:
import torch

# 3x4 크기의 2차원 텐서 생성
x = torch.tensor([[ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12]])

# 1. 단일 요소 접근 (1행 2열 -> 값: 7)
print(f'x: {x[1,2]}')                # 7
print(f'x: {x[1,2].item()}')                # 7

# 2. 특정 행/열 전체 추출
print("2-1. 첫 번째 행 전체 (0, :):", x[0, :])
print("2-2. 마지막 열 전체 (:, -1):", x[:, -1])

# 3. 범위 슬라이싱 (0~1행, 1~2열 추출)
# [start:end]에서 end는 포함되지 않음
print("3. 부분 텐서 추출:\n", x[0:2, 1:3])

# 4. 간격 지정 슬라이싱 (step=2)
print("4. 2칸 간격 추출:", x[:, ::2])

x: 7
x: 7
2-1. 첫 번째 행 전체 (0, :): tensor([1, 2, 3, 4])
2-2. 마지막 열 전체 (:, -1): tensor([ 4,  8, 12])
3. 부분 텐서 추출:
 tensor([[2, 3],
        [6, 7]])
4. 2칸 간격 추출: tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])


## 3.2 고급 인덱싱 (Advanced Indexing)

조건을 이용해 데이터를 필터링하는 **불리언 마스킹**과 특정 위치의 인덱스를 배열로 전달해 가져오는 **팬시 인덱싱** 방식입니다.

### 주요 개념

- **불리언 마스킹 (Boolean Indexing):** 텐서에 조건식을 적용하여 `True` 위치의 값만 1차원 텐서로 추출합니다.
- **`torch.index_select()`:** 특정 차원(`dim`)을 기준으로 원하는 인덱스 번호 들을 모아서 선택합니다.

In [16]:
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

# 1. 불리언 마스킹 (50보다 큰 요소만 추출)
mask = x > 50
print("마스크 (Boolean Tensor):\n", mask)
print("50보다 큰 값만 추출:", x[mask])  # 1차원 텐서로 반환됨

# 2. 인덱스 리스트를 활용한 추출 (팬시 인덱싱)
# 0행과 2행 추출
rows = torch.tensor([0, 2])
print("\n0행과 2행 추출:\n", x[rows])

# 3. torch.index_select 사용 (dim=1: 열 기준 추출)
cols = torch.tensor([0, 2]) # 0열과 2열 선택
selected_cols = torch.index_select(x, dim=1, index=cols)
print("0열과 2열 추출 (index_select):\n", selected_cols)

마스크 (Boolean Tensor):
 tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
50보다 큰 값만 추출: tensor([60, 70, 80, 90])

0행과 2행 추출:
 tensor([[10, 20, 30],
        [70, 80, 90]])
0열과 2열 추출 (index_select):
 tensor([[10, 30],
        [40, 60],
        [70, 90]])
